# Site Settings
encoding                 : "utf-8"
locale                   : "en"
title                    : "AtomTech"
description              : "Affordable Tech Help Made Easy."
favicon                  : "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxzdmcKICAgd2lkdGg9IjI0IgogICBoZWlnaHQ9IjIwLjk3MTA5IgogICB4bWw6c3BhY2U9InByZXNlcnZlIgogICB2ZXJzaW9uPSIxLjEiCiAgIGlkPSJzdmcxIgogICBzb2RpcG9kaTpkb2NuYW1lPSJsb2dvLWJsdWUtYXRvbXRlY2gtZmF2aWNvbi5zdmciCiAgIGlua3NjYXBlOnZlcnNpb249IjEuNCAoODZhOGFkNywgMjAyNC0xMC0xMSkiCiAgIHhtbG5zOmlua3NjYXBlPSJodHRwOi8vd3d3Lmlua3NjYXBlLm9yZy9uYW1lc3BhY2VzL2lua3NjYXBlIgogICB4bWxuczpzb2RpcG9kaT0iaHR0cDovL3NvZGlwb2RpLnNvdXJjZWZvcmdlLm5ldC9EVEQvc29kaXBvZGktMC5kdGQiCiAgIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICAgeG1sbnM6c3ZnPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGRlZnMKICAgaWQ9ImRlZnMxIiAvPjxzb2RpcG9kaTpuYW1lZHZpZXcKICAgaWQ9Im5hbWVkdmlldzEiCiAgIHBhZ2Vjb2xvcj0iI2ZmZmZmZiIKICAgYm9yZGVyY29sb3I9IiMwMDAwMDAiCiAgIGJvcmRlcm9wYWNpdHk9IjAuMjUiCiAgIGlua3NjYXBlOnNob3dwYWdlc2hhZG93PSIyIgogICBpbmtzY2FwZTpwYWdlb3BhY2l0eT0iMC4wIgogICBpbmtzY2FwZTpwYWdlY2hlY2tlcmJvYXJkPSIwIgogICBpbmtzY2FwZTpkZXNrY29sb3I9IiNkMWQxZDEiCiAgIGlua3NjYXBlOnpvb209IjEzLjYyMTk1MSIKICAgaW5rc2NhcGU6Y3g9IjIzLjUyODIwMSIKICAgaW5rc2NhcGU6Y3k9IjEuMDY0NDU4NCIKICAgaW5rc2NhcGU6d2luZG93LXdpZHRoPSIyMjU2IgogICBpbmtzY2FwZTp3aW5kb3ctaGVpZ2h0PSIxMzk4IgogICBpbmtzY2FwZTp3aW5kb3cteD0iLTExIgogICBpbmtzY2FwZTp3aW5kb3cteT0iLTExIgogICBpbmtzY2FwZTp3aW5kb3ctbWF4aW1pemVkPSIxIgogICBpbmtzY2FwZTpjdXJyZW50LWxheWVyPSJzdmcxIiAvPgoKIDxnCiAgIGlkPSJnMSIKICAgdHJhbnNmb3JtPSJtYXRyaXgoMC41MTA2MzgzLDAsMCwwLjUxMDYzODMsMCwtMjAuOTI1MzU4KSI+CiAgPHRpdGxlCiAgIGlkPSJ0aXRsZTEiPkxheWVyIDE8L3RpdGxlPgogIDxyZWN0CiAgIGZpbGw9IiMzYjZkZWMiCiAgIGhlaWdodD0iMS4zIgogICB3aWR0aD0iMS40IgogICBjbGFzcz0ic3QxIgogICB5PSI0NS43MDAwMDEiCiAgIHg9IjIyLjUiCiAgIGlkPSJSZWN0YW5nbGVfMS0yIiAvPgogIDxjaXJjbGUKICAgZmlsbD0iIzNiNmRlYyIKICAgcj0iMi4zIgogICBjeT0iNjEuMjk5OTk5IgogICBjeD0iMzUuMDk5OTk4IgogICBjbGFzcz0ic3QxIgogICBpZD0iRWxsaXBzZV8xLTIiIC8+CiAgPGNpcmNsZQogICBmaWxsPSIjM2I2ZGVjIgogICBjeT0iNjEuNSIKICAgY3g9IjIzLjQiCiAgIGNsYXNzPSJzdDEiCiAgIGlkPSJFbGxpcHNlXzItMiIKICAgcj0iNC4xOTk5OTk4IiAvPgogIDxwYXRoCiAgIGZpbGw9IiMzYjZkZWMiCiAgIGQ9Im0gMzUuNyw2My41IGMgLTAuNiwtMS40IC0xLjIsLTIuNyAtMS45LC00LjEgLTAuNiwwLjQgLTEsMS4xIC0xLDEuOSAwLDAgMCwwIDAsMCAwLjMsMC42IDAuNiwxLjIgMC45LDEuOCAwLjQsMC4zIDAuOSwwLjUgMS40LDAuNSAwLjIsMCAwLjQsMCAwLjYsLTAuMSB6IgogICBjbGFzcz0ic3QxIgogICBpZD0iUGF0aF8xLTIiIC8+CiAgPHBhdGgKICAgZmlsbD0iIzNiNmRlYyIKICAgZD0ibSAzMy42LDYzLjggYyAtMC41LDAuOCAtMTMuMiwyMC45IC0yMiwxNi43IC0xMC4xLC00LjkgMTMuNSwtNDMuNyAyMy43LC0zOCA0LjksMi42IDEsMTUuMSAwLjcsMTYgdiAwIGMgNS41LC0xNC45IC0wLjIsLTE2LjggLTAuMiwtMTYuOCAtMTMsLTYuNCAtMzYsMzIuNSAtMjQuNywzOS42IDkuOCw0LjggMjIsLTE2LjYgMjIuNSwtMTcuNSB6IgogICBjbGFzcz0ic3QxIgogICBpZD0iUGF0aF8yLTIiIC8+CiAgPHBhdGgKICAgZmlsbD0iIzNiNmRlYyIKICAgZD0ibSAzNS44NDIsNjQuMDM5IGMgLTAuMywwLjEgLTAuNiwwLjEgLTAuOCwwLjEgLTAuMywwIC0wLjcsLTAuMSAtMSwtMC4yIDMuNCw3LjUgNC42LDE0LjYgMC43LDE2LjUgLTQuNywyLjQgLTEwLjcsLTIuNiAtMTUuMSwtNy44IC0wLjEsMC4xIC0wLjMsMC4yIC0wLjQsMC4zIDQuNSw1LjYgMTAuNiwxMS4xIDE2LDguNCA0LjIsLTIuNyAzLjYsLTkuOCAwLjYsLTE3LjMgeiIKICAgY2xhc3M9InN0MSIKICAgaWQ9IlBhdGhfNC0yIiAvPgogIDxwYXRoCiAgIGZpbGw9IiMzYjZkZWMiCiAgIGQ9Im0gMTYuMzQyLDY4LjUzOSBjIC0yLC0yLjcgLTMuMywtNC44IC0zLjMsLTQuOCAwLDAgMS4yLDIuMSAzLjEsNSAwLjEsLTAuMSAwLjEsLTAuMSAwLjIsLTAuMiB6IgogICBjbGFzcz0ic3QxIgogICBpZD0iUGF0aF81LTIiIC8+CiAgPGNpcmNsZQogICBmaWxsPSIjM2I2ZGVjIgogICByPSIyIgogICBjeT0iNTQuMDk5OTk4IgogICBjeD0iOS4xOTk5OTk4IgogICBjbGFzcz0ic3QxIgogICBpZD0iRWxsaXBzZV80LTIiIC8+CiAgPHBhdGgKICAgZmlsbD0iIzNiNmRlYyIKICAgZD0ibSAyMy41LDUxLjcxOSBjIC00LDAgLTgsMC40IC0xMS45LDEuMyAwLjEsMC4xIDAuMSwwLjMgMC4xLDAuNCAzLjgsLTAuOSA3LjgsLTEuNCAxMS43LC0xLjQgMTIuNCwwIDIyLjQsNC4yIDIyLjQsOS40IDAsNS4yIC0xMCw5LjQgLTIyLjQsOS40IC0xMi40LDAgLTIyLjMsLTQuMSAtMjIuMywtOS4zIDAsLTIuNCAyLjIsLTQuNiA1LjcsLTYuMyAtMC4xLC0wLjIgLTAuMSwtMC4zIC0wLjIsLTAuNSAtNC4xLDEuNyAtNi42LDQuMSAtNi42LDYuOCAwLDUuNCAxMC41LDkuOCAyMy41LDkuOCAxMywwIDIzLjUsLTQuNCAyMy41LC05LjggMCwtNS40IC0xMC41LC05LjggLTIzLjUsLTkuOCB6IgogICBjbGFzcz0ic3QxIgogICBpZD0iUGF0aF82LTIiIC8+CiAgPHBhdGgKICAgZmlsbD0iIzNiNmRlYyIKICAgZD0ibSA5LjkyOSw1Ni43IGMgMC4yLDAuNiAwLjQsMS4zIDAuNywxLjkgMC40LDEgLTAuMiwtMC44IC0wLjYsLTIgeiIKICAgY2xhc3M9InN0MSIKICAgaWQ9IlBhdGhfOC0yIiAvPgogIDxwYXRoCiAgIGZpbGw9IiMzYjZkZWMiCiAgIGQ9Im0gMTAuNzI5LDQxLjcgYyAwLDAgLTMuNywxLjMgLTIuMiw5LjkgMC4xLDAgMC4zLC0wLjEgMC41LC0wLjEgLTAuNCwtMy43IC0wLjMsLTcuNyAyLjIsLTkgNS41LC0zLjEgMTUuMSw3LjIgMjAuOSwxOCAwLjIsLTAuNiAwLjYsLTEuMiAxLjIsLTEuNSAtNS44LC0xMSAtMTUuNiwtMjAuOCAtMjIuNiwtMTcuMyB6IgogICBjbGFzcz0ic3QxIgogICBpZD0iUGF0aF8xMC0yIiAvPgogIDxwYXRoCiAgIGlkPSJzdmdfMSIKICAgZD0iTSA4LjY4NjU1LDUwLjUzODk4IgogICBvcGFjaXR5PSIwIgogICBzdHJva2U9IiMwMDAwMDAiCiAgIGZpbGw9IiMzYjZkZWMiIC8+CiAgPGNpcmNsZQogICBmaWxsPSIjM2I2ZGVjIgogICByPSIyIgogICBjeT0iNzAuNjk5OTk3IgogICBjeD0iMTcuNzk5OTk5IgogICBjbGFzcz0ic3QxIgogICBpZD0iRWxsaXBzZV8zLTIiIC8+CiA8L2c+Cjwvc3ZnPgo="
avatar                   : "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxzdmcKICAgd2lkdGg9IjEyNiIKICAgaGVpZ2h0PSIxMTAuMDk4MjMiCiAgIHhtbDpzcGFjZT0icHJlc2VydmUiCiAgIHZlcnNpb249IjEuMSIKICAgaWQ9InN2ZzEiCiAgIHNvZGlwb2RpOmRvY25hbWU9ImxvZ28tYmx1ZS1hdG9tdGVjaC5zdmciCiAgIGlua3NjYXBlOnZlcnNpb249IjEuNCAoODZhOGFkNywgMjAyNC0xMC0xMSkiCiAgIHhtbG5zOmlua3NjYXBlPSJodHRwOi8vd3d3Lmlua3NjYXBlLm9yZy9uYW1lc3BhY2VzL2lua3NjYXBlIgogICB4bWxuczpzb2RpcG9kaT0iaHR0cDovL3NvZGlwb2RpLnNvdXJjZWZvcmdlLm5ldC9EVEQvc29kaXBvZGktMC5kdGQiCiAgIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICAgeG1sbnM6c3ZnPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGRlZnMKICAgaWQ9ImRlZnMxIiAvPjxzb2RpcG9kaTpuYW1lZHZpZXcKICAgaWQ9Im5hbWVkdmlldzEiCiAgIHBhZ2Vjb2xvcj0iI2ZmZmZmZiIKICAgYm9yZGVyY29sb3I9IiMwMDAwMDAiCiAgIGJvcmRlcm9wYWNpdHk9IjAuMjUiCiAgIGlua3NjYXBlOnNob3dwYWdlc2hhZG93PSIyIgogICBpbmtzY2FwZTpwYWdlb3BhY2l0eT0iMC4wIgogICBpbmtzY2FwZTpwYWdlY2hlY2tlcmJvYXJkPSIwIgogICBpbmtzY2FwZTpkZXNrY29sb3I9IiNkMWQxZDEiCiAgIGlua3NjYXBlOnpvb209IjEzLjYyMTk1MSIKICAgaW5rc2NhcGU6Y3g9IjIzLjUyODIwMSIKICAgaW5rc2NhcGU6Y3k9IjEuMDY0NDU4NCIKICAgaW5rc2NhcGU6d2luZG93LXdpZHRoPSIyMjU2IgogICBpbmtzY2FwZTp3aW5kb3ctaGVpZ2h0PSIxMzk4IgogICBpbmtzY2FwZTp3aW5kb3cteD0iLTExIgogICBpbmtzY2FwZTp3aW5kb3cteT0iLTExIgogICBpbmtzY2FwZTp3aW5kb3ctbWF4aW1pemVkPSIxIgogICBpbmtzY2FwZTpjdXJyZW50LWxheWVyPSJzdmcxIiAvPgoKIDxnCiAgIGlkPSJnMSIKICAgdHJhbnNmb3JtPSJtYXRyaXgoMi42ODA4NTExLDAsMCwyLjY4MDg1MTEsMCwtMTA5Ljg1ODEzKSI+CiAgPHRpdGxlCiAgIGlkPSJ0aXRsZTEiPkxheWVyIDE8L3RpdGxlPgogIDxyZWN0CiAgIGZpbGw9IiMzYjZkZWMiCiAgIGhlaWdodD0iMS4zIgogICB3aWR0aD0iMS40IgogICBjbGFzcz0ic3QxIgogICB5PSI0NS43MDAwMDEiCiAgIHg9IjIyLjUiCiAgIGlkPSJSZWN0YW5nbGVfMS0yIiAvPgogIDxjaXJjbGUKICAgZmlsbD0iIzNiNmRlYyIKICAgcj0iMi4zIgogICBjeT0iNjEuMjk5OTk5IgogICBjeD0iMzUuMDk5OTk4IgogICBjbGFzcz0ic3QxIgogICBpZD0iRWxsaXBzZV8xLTIiIC8+CiAgPGNpcmNsZQogICBmaWxsPSIjM2I2ZGVjIgogICBjeT0iNjEuNSIKICAgY3g9IjIzLjQiCiAgIGNsYXNzPSJzdDEiCiAgIGlkPSJFbGxpcHNlXzItMiIKICAgcj0iNC4xOTk5OTk4IiAvPgogIDxwYXRoCiAgIGZpbGw9IiMzYjZkZWMiCiAgIGQ9Im0gMzUuNyw2My41IGMgLTAuNiwtMS40IC0xLjIsLTIuNyAtMS45LC00LjEgLTAuNiwwLjQgLTEsMS4xIC0xLDEuOSAwLDAgMCwwIDAsMCAwLjMsMC42IDAuNiwxLjIgMC45LDEuOCAwLjQsMC4zIDAuOSwwLjUgMS40LDAuNSAwLjIsMCAwLjQsMCAwLjYsLTAuMSB6IgogICBjbGFzcz0ic3QxIgogICBpZD0iUGF0aF8xLTIiIC8+CiAgPHBhdGgKICAgZmlsbD0iIzNiNmRlYyIKICAgZD0ibSAzMy42LDYzLjggYyAtMC41LDAuOCAtMTMuMiwyMC45IC0yMiwxNi43IC0xMC4xLC00LjkgMTMuNSwtNDMuNyAyMy43LC0zOCA0LjksMi42IDEsMTUuMSAwLjcsMTYgdiAwIGMgNS41LC0xNC45IC0wLjIsLTE2LjggLTAuMiwtMTYuOCAtMTMsLTYuNCAtMzYsMzIuNSAtMjQuNywzOS42IDkuOCw0LjggMjIsLTE2LjYgMjIuNSwtMTcuNSB6IgogICBjbGFzcz0ic3QxIgogICBpZD0iUGF0aF8yLTIiIC8+CiAgPHBhdGgKICAgZmlsbD0iIzNiNmRlYyIKICAgZD0ibSAzNS44NDIsNjQuMDM5IGMgLTAuMywwLjEgLTAuNiwwLjEgLTAuOCwwLjEgLTAuMywwIC0wLjcsLTAuMSAtMSwtMC4yIDMuNCw3LjUgNC42LDE0LjYgMC43LDE2LjUgLTQuNywyLjQgLTEwLjcsLTIuNiAtMTUuMSwtNy44IC0wLjEsMC4xIC0wLjMsMC4yIC0wLjQsMC4zIDQuNSw1LjYgMTAuNiwxMS4xIDE2LDguNCA0LjIsLTIuNyAzLjYsLTkuOCAwLjYsLTE3LjMgeiIKICAgY2xhc3M9InN0MSIKICAgaWQ9IlBhdGhfNC0yIiAvPgogIDxwYXRoCiAgIGZpbGw9IiMzYjZkZWMiCiAgIGQ9Im0gMTYuMzQyLDY4LjUzOSBjIC0yLC0yLjcgLTMuMywtNC44IC0zLjMsLTQuOCAwLDAgMS4yLDIuMSAzLjEsNSAwLjEsLTAuMSAwLjEsLTAuMSAwLjIsLTAuMiB6IgogICBjbGFzcz0ic3QxIgogICBpZD0iUGF0aF81LTIiIC8+CiAgPGNpcmNsZQogICBmaWxsPSIjM2I2ZGVjIgogICByPSIyIgogICBjeT0iNTQuMDk5OTk4IgogICBjeD0iOS4xOTk5OTk4IgogICBjbGFzcz0ic3QxIgogICBpZD0iRWxsaXBzZV80LTIiIC8+CiAgPHBhdGgKICAgZmlsbD0iIzNiNmRlYyIKICAgZD0ibSAyMy41LDUxLjcxOSBjIC00LDAgLTgsMC40IC0xMS45LDEuMyAwLjEsMC4xIDAuMSwwLjMgMC4xLDAuNCAzLjgsLTAuOSA3LjgsLTEuNCAxMS43LC0xLjQgMTIuNCwwIDIyLjQsNC4yIDIyLjQsOS40IDAsNS4yIC0xMCw5LjQgLTIyLjQsOS40IC0xMi40LDAgLTIyLjMsLTQuMSAtMjIuMywtOS4zIDAsLTIuNCAyLjIsLTQuNiA1LjcsLTYuMyAtMC4xLC0wLjIgLTAuMSwtMC4zIC0wLjIsLTAuNSAtNC4xLDEuNyAtNi42LDQuMSAtNi42LDYuOCAwLDUuNCAxMC41LDkuOCAyMy41LDkuOCAxMywwIDIzLjUsLTQuNCAyMy41LC05LjggMCwtNS40IC0xMC41LC05LjggLTIzLjUsLTkuOCB6IgogICBjbGFzcz0ic3QxIgogICBpZD0iUGF0aF82LTIiIC8+CiAgPHBhdGgKICAgZmlsbD0iIzNiNmRlYyIKICAgZD0ibSA5LjkyOSw1Ni43IGMgMC4yLDAuNiAwLjQsMS4zIDAuNywxLjkgMC40LDEgLTAuMiwtMC44IC0wLjYsLTIgeiIKICAgY2xhc3M9InN0MSIKICAgaWQ9IlBhdGhfOC0yIiAvPgogIDxwYXRoCiAgIGZpbGw9IiMzYjZkZWMiCiAgIGQ9Im0gMTAuNzI5LDQxLjcgYyAwLDAgLTMuNywxLjMgLTIuMiw5LjkgMC4xLDAgMC4zLC0wLjEgMC41LC0wLjEgLTAuNCwtMy43IC0wLjMsLTcuNyAyLjIsLTkgNS41LC0zLjEgMTUuMSw3LjIgMjAuOSwxOCAwLjIsLTAuNiAwLjYsLTEuMiAxLjIsLTEuNSAtNS44LC0xMSAtMTUuNiwtMjAuOCAtMjIuNiwtMTcuMyB6IgogICBjbGFzcz0ic3QxIgogICBpZD0iUGF0aF8xMC0yIiAvPgogIDxwYXRoCiAgIGlkPSJzdmdfMSIKICAgZD0iTSA4LjY4NjU1LDUwLjUzODk4IgogICBvcGFjaXR5PSIwIgogICBzdHJva2U9IiMwMDAwMDAiCiAgIGZpbGw9IiMzYjZkZWMiIC8+CiAgPGNpcmNsZQogICBmaWxsPSIjM2I2ZGVjIgogICByPSIyIgogICBjeT0iNzAuNjk5OTk3IgogICBjeD0iMTcuNzk5OTk5IgogICBjbGFzcz0ic3QxIgogICBpZD0iRWxsaXBzZV8zLTIiIC8+CiA8L2c+Cjwvc3ZnPgo="
url                      : "https://tech.atomtroxell.com" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog" leave blank if no subpath

publish_mode: editorial_workflow # required for Netlify
future: true # if the post's date is in the future

# Site Author
author:
  name                   : "AtomTech" # appears in the footer and atom feed

comments                 : false # set it to false to disable comments
disqus:
  shortname              : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-

atom_feed:
  path                   : # blank (default) uses feed.xml

og_image                 : "/assets/images/mighil.png" # Open Graph/Twitter default site image, optional for seo and social sharing

# Social sharing
# twitter:
#   username               : verfasor # optional, for social sharing

# Analytics
analytics:
  google:
    tracking_id          : UA-128372009-1 # add your google tracking id here

# Reading Files
include:
  - _pages
  - "_redirects"
# Files excluded from Jekyll builds
exclude:
- README.md
- LICENSE
- Gemfile
- Gemfile.lock


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:title/
# paginate: 5 # amount of posts to show
# paginate_path: "/blog/page:num/"
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# collections:
#   poetry:
#     output: true
#     permalink: /:collection/:title/

# Plugins
gems:
  # - jekyll-paginate
  - jekyll-feed

# mimic GitHub Pages with --safe
whitelist:
  # - jekyll-paginate
  - jekyll-feed


# Front matter defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      comments: false
  - scope:
      path: "/contact"
      type: pages
    values:
      layout: page
      comments: false
  # _posts
  # - scope:
  #     path: ""
  #     type: posts
  #   values:
  #     layout: post
  #     comments: true
  #     share: true
  # _poetry
  # - scope:
  #     path: ""
  #     type: poetry
  #   values:
  #     layout: post
  #     share: false
  # _exclude    
exclude:
         - vendor
         - Gemfile
         - Gemfile.lock
         - node_modules
         - gulpfile.js
         - package.json